### PR TITLE
Corrected the Typo in the Spelling of Cholesterol

### LINKED ISSUE #41841: Typo in Data Analysis - Medical Data Visualizer
**Describe your problem and how to reproduce it:**
In the below comment, 'cholestorol' should be spelt 'cholesterol'

Normalize data by making 0 always good and 1 always bad. If the value of 'cholestorol' or 'gluc' is 1, make the value 0. If the value is more than 1, make the value 1.

**Add a Link to the page with the problem:**
https://github.com/freeCodeCamp/boilerplate-medical-data-visualizer/blob/master/medical_data_visualizer.py

### PR DESCRIPTION
**Pull request by ghost**
Checklist:

- [x] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [x] My pull request has a descriptive title (not a vague title like `Update index.md`)

Closes https://github.com/freeCodeCamp/freeCodeCamp/issues/41841

In one of the comments in main.py, cholesterol was spelt 'cholestorol, this pr fixes this.

### CODE REVIEW

**Review by gikf — COMMENTED** [review]
Looks like some additional files from the `.history/` folder got attached to this PR, they will need to be removed before PR can be accepted.

**Comment by ghost** [comment]
@gikf, yeah I forgot to take notice of that! thanks for pointing that out. Please have a look now.

**Review by gikf — APPROVED** [review]
LGTM :+1:

**Review by Sembauke — APPROVED** [review]
LGTM 👍

**Pull request merged**
