### PR TITLE
fix(i18n) : add numbers to label comments 

### PR DESCRIPTION
**Pull request by a2937**
Checklist:

- [X] I have read [freeCodeCamp's contribution guidelines](https://contribute.freecodecamp.org).
- [X] My pull request has a [descriptive title](https://contribute.freecodecamp.org/#/how-to-open-a-pull-request?id=prepare-a-good-pr-title) (**not** a vague title like `Update index.md`)

Related to freecodecamp/freecodecamp#47038 

I tried to match a few comments up with the tasks.  I think I need something clarified.

### CODE REVIEW

**Comment by jdwilkin4** [comment]
Hey @a2937 ! 

Just checking in to see if you are still working on this PR since it was in draft status.
Thanks 👍

**Comment by a2937** [comment]
I think I never moved it from draft because I needed help with something.

**Comment by jdwilkin4** [comment]
@a2937 

Sorry for the delayed response.

Were you able to get resolution on your issue?
If not, then you can reach out on the freeCodeCamp forum or discord for help 👍

**Comment by naomi-lgbt** [comment]
Hiya,

Did you still need clarification/help on this one?

**Comment by a2937** [comment]
The problem I had a really long time ago with this one that not all the comments and directions truly matched up 1 to 1. I mean they were close but not exact. It was kinda tripping me up. If it's in a good state right now, then let's merge it. If not, I can figure out what to actually do and finally solve this.

**Comment by naomi-lgbt** [comment]
Unfortunately, we can't land this until the challenge instructions are updated on /learn.

If you're interested in taking that on, let me know. Otherwise, I can add it to my backlog.

**Comment by a2937** [comment]
I wanna tackle this, provided the instructions on what needs is updated is relatively clear.

**Comment by naomi-lgbt** [comment]
Whoops! These landed on learn a long time ago. Let's get this in.

**Pull request merged**
